# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Updatecli Installer'
description: 'Install a specific Updatecli version'
author: 'Updatecli'
branding:
  icon: 'fast-forward'
  color: 'purple'
inputs:
  version:
    description: 'Specify Updatecli version to use. Accepted values are any Updatecli version'
  version-file:
    description: 'The path to the `.updatecli-version` file. See examples of supported syntax in README file'
runs:
  using: 'node20'
  main: 'dist/index.js'
